CREATE DATABASE IF NOT EXISTS `lm1`;
CREATE DATABASE IF NOT EXISTS `lm1_testing`;
GRANT ALL PRIVILEGES ON `lm1`.* TO 'lm1-user'@'%';
GRANT ALL PRIVILEGES ON `lm1_testing`.* TO 'lm1-user'@'%';
FLUSH  PRIVILEGES;